apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: purchase-order
  name: purchase-order
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 60
  selector:
    matchLabels:
      app: purchase-order
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: purchase-order
    spec:
      containers:
        - image: staillansag/msr-dec-purchase-order:latest
          imagePullPolicy: Always
          name: purchase-order-msr
          ports:
            - name: metrics
              containerPort: 5555
          volumeMounts:
            - mountPath: "/tmp/license"
              name: licenses
              readOnly: true
          env:
            - name: SAG_IS_CONFIG_PROPERTIES
              value: /opt/softwareag/IntegrationServer/packages/DecPurchaseOrder/application.properties   
            - name: SERVER_LOCATION
              value: kubernetes
            - name: DATASOURCE_CLASS
              value: org.postgresql.ds.PGSimpleDataSource
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: databaseUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: databasePassword
            - name: DB_SERVERNAME
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: databaseServerName
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: databaseServerPort
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: databaseName
            - name: MSR_URL
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: domainName
            - name: IO_INT_URL
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: wmioIntegrationPlaygroundUrl
            - name: IO_INT_USER
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: wmioIntegrationPlaygroundUser
            - name: IO_INT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: environment-secrets
                  key: wmioIntegrationPlaygroundPassword
            - name: KAFKA_SERVER_LIST
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: kafkaServerList
          livenessProbe:
            tcpSocket:
              port: 5555
            initialDelaySeconds: 180
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5555
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 12
      volumes:
        - name: licenses
          secret:
            secretName: licenses
