apiVersion: v1
kind: Service
metadata:
  name: msr-purchase-order
  labels:
    name: msr-purchase-order
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - port: 5115
    targetPort: 5555
    name: msr-purchase-order-admin
  - port: 5119
    targetPort: 9999
    name: msr-purchase-order-diag
  selector:
    app: purchase-order
