{
 "title": "Purchase Order monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MSR CPU usage ($pod)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "repeat": "pod",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sag_is_server_proc_cpu_percent{app=\"purchase-order\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MSR used memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sag_is_used_memory_bytes{app=\"purchase-order\", kubernetes_pod_name=~\"$pod\"} / 1000000",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "MSR CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sag_is_server_proc_cpu_percent{app=\"purchase-order\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of service errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sag_is_number_service_errors{app=\"purchase-order\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sag_is_total_http_requests{app=\"purchase-order\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}