# My News Service build pipeline

trigger: 
  - main
  - master
  - feature*

pool:
  name: Default

variables:
  - group: customer-management-options

stages:

- stage: Build

  jobs:

  - job: BuildImage

    steps:

    - task: DownloadSecureFile@1
      displayName: 'Download test environment config file'
      name: dockerEnv
      inputs:
        secureFile: 'dec-purchase-order-qa.env'  

    - task: DownloadSecureFile@1
      name: CRCredentials
      displayName: 'Download container registry credentials'
      inputs:
        secureFile: 'cr.credentials.sh'

    - task: DownloadSecureFile@1
      name: AzureSPCredentials
      displayName: 'Download Azure SP credentials'
      inputs:
        secureFile: 'azure.sp.credentials.sh'

    - script: chmod u+x ./resources/buildScripts/*.sh
      displayName: "Grant shell execution permissions"

    - script: ./resources/buildScripts/01.setJobInitialVariables.sh
      displayName: 'Set job variables'

    - script: ./resources/buildScripts/02.prepareAgentMachineV3.sh
      displayName: 'Prepare agent'

    - script: ./resources/buildScripts/04.buildV2.sh
      displayName: 'Build and push image'

- stage: Deploy
  dependsOn: Build

  jobs:

  - job: DeployKubernetes

    steps:  

    - task: DownloadSecureFile@1
      name: kubernetesSecrets
      displayName: 'Download kubernetes secrets'
      inputs:
        secureFile: 'kubernetes-secrets.yaml'

    - task: DownloadSecureFile@1
      name: KubernetesConfigMap
      displayName: 'Download Kubernetes config map'
      inputs:
        secureFile: '00_msr-purchase-order_configMap.yaml'

    - task: DownloadSecureFile@1
      name: KubernetesSecret
      displayName: 'Download Kubernetes secret'
      inputs:
        secureFile: '00_msr-purchase-order_secret.yaml'

    - script: chmod u+x ./resources/buildScripts/*.sh
      displayName: "Grant shell execution permissions"

    - script: ./resources/buildScripts/06.deployKubernetes.sh
      displayName: 'Deploy image to Kubernetes'

  - job: AutomatedTestsProd
    dependsOn: DeployKubernetes

    steps:

    - task: DownloadSecureFile@1
      name: postmanEnvironmentProdMsr
      displayName: 'Download Postman Prod environment file'
      inputs:
        secureFile: 'DecPurchaseOrder.postman_environment.json'

    - script: chmod u+x ./resources/buildScripts/*.sh
      displayName: "Grant shell execution permissions"
      
    - script: ./resources/buildScripts/88.automatedTests.sh
      displayName: 'Perform automated tests'

  - job: RollbackKubernetesDeployment
    dependsOn: 
    - DeployKubernetes
    - AutomatedTestsProd
    condition: |
      or
      (
        eq(dependencies.DeployKubernetes.result, 'Failed'),
        eq(dependencies.AutomatedTestsProd.result, 'Failed')
      )

    steps:

    - script: chmod u+x ./resources/buildScripts/*.sh
      displayName: "Grant shell execution permissions"

    - script: ./resources/buildScripts/90.rollbackKubernetesDeployment.sh
      displayName: 'Rollback Kubernetes deployment'
